### ISSUE TITLE
dynamic get table‘s data

### ISSUE THREAD

**Issue by ElanUpper** [SAP/PyHDB#81]
for example, I want get the data, but I don't know the tablename. so I need to write the stament like following:
`QueryData = 'select * from :1;' `
`curWrite.execute(QueryColumn, [tableName]).fetchall();
`
but colsole return "incorrect syntax near ":1""

**Comment by TwoLaid** [comment]
As far as I know, table names cannot be used as query parameters.

Alternatively, you could just use something like `format` from Python itself:

```
query = 'SELECT 1 FROM "{}"'.format(tableName)
cursor.execute(query).fetchall()
```

Please keep in mind that you might want to sanitize `tableName` if it comes from user input that can be manipulated. Otherwise you might be vulnerable to SQL injection

**Comment by jarus** [comment]
The comment from @TwoLaid is 100% correct. The table name can't be used as query parameter as the table name is mandatory at SQL compile time.
